test/librados: fix boost error code assertions
The librados asio tests compare boost::system::error_code and
boost::system::errc errors, failing on Windows:

    ft2.4: ceph_test_rados_api_asio.AsioRados.AsyncWriteCallbacktesttools.
      testresult.real._StringException: details: {{{
    /ceph/src/test/librados/asio.cc:148
    Expected equality of these values:
      boost::system::errc::read_only_file_system
        Which is: 30
      ec
        Which is: system:30
    }}}

We'll update the assertions, retrieving the error code value.

Signed-off-by: Lucian Petrut <lpetrut@cloudbasesolutions.com>